### PR TITLE
Gem clean up

### PR DESCRIPTION
**Pull request by bensymonds**
What do you guys think about this, particularly the "rearrange gemfile" commit?

### CODE REVIEW

**Comment by erino** [comment]
I think it's not obvious that if you add a gem to the `test` group it won't be installed on the CI server.

**Comment by bensymonds** [comment]
Well it would become clear relatively quickly :smile:. And also it's not _obvious_ obvious, but it's still pretty obvious if you look at the structure of the file. But I take your point.

In case it helps, I forgot to mention this _is_ what [rails does](https://github.com/rails/rails/blob/master/.travis.yml#L43).

We could just wrap all the non-CI gems in the `development` group, and then get rid of `test` group completely..?

**Comment by jgwhite** [comment]
> We could just wrap all the non-CI gems in the development group, and then get rid of test group completely..?

This sounds like a good approach.

**Comment by bensymonds** [comment]
@erino @jgwhite updated. I added another couple of commits too.

**Comment by jgwhite** [comment]
This looks good.

We often drop a `debugger` into a file whilst running tests — should `debugger` and `pry-rails` therefore be in the `test` group too?

**Comment by jgwhite** [comment]
And actually, while we’re on this topic… 3 debugger-type libraries? Shall we pick just one? Or am I missing their subtly different purposes?

**Comment by bensymonds** [comment]
Well that's the thing, now there is no explicit `test` group - it's effectively `development`. So having them in there is enough for them to work in tests too.

Re. the debugging libraries - well `pry-rails` doesn't add a debugger, so that doesn't count. And then the other two are for different versions of ruby, so you need them both as long as you support 1.9 and 2.

**Comment by jgwhite** [comment]
Ah, in that case I misunderstood how Rails loads bundler groups. I assumed `:development` was not loaded for tests.

I like pry, but should we drop `pry-rails` for simplicity?

**Comment by bensymonds** [comment]
Ok you win 5p, because you are right, Rails does not normally load `development` group in `test` mode. It's just because we have [this](https://github.com/withassociates/slices/blob/master/spec/spec_helper.rb#L4) (notice the lack of args) that it works. It's not normal to have that. E.g. follow it through in `https://github.com/withassociates/with-pair` and you end up [here](https://github.com/withassociates/with-pair/blob/master/config/application.rb#L11). I don't know where it came from.

**Comment by bensymonds** [comment]
I would happily drop `pry-rails`. Actually I noticed [this](https://github.com/rails/rails/blob/master/Gemfile#L65) snippet in Rails' gemfile, which I like. I mean, just because Dave likes `awesome_print`, why does _everyone_ have to install it? So that snippet allows Dave to have it without affecting everyone else (unless his local gems start putting constraints on the rest of them, which would not be cool).

**Comment by jgwhite** [comment]
@bensymonds I’m :+1: for removing pry-rails and introducing the `.Gemfile` (though in a separate pass).

**Comment by bensymonds** [comment]
Yep agree about not bothering with `.Gemfile` for now.

With `pry-rails` removal, the problem is that, to a certain extent, even the need for having debugging gems is subjective. So there's a case to be made for removing them too! Really there's not much you'd ever have in your `development` group that is actually _required_. Looking at a couple of other projects, the only one I can see is `capistrano`. Thinking about it, the `development` group is, by definition, the group for humans' gems. So it makes sense it's heavily subjective.

So anyway, I think I might leave `pry-rails` for now, and address another time.

**Comment by jgwhite** [comment]
Fair enough. Other than that, LGTM.

**Comment by bensymonds** [comment]
@erino what about you?

**Comment by erino** [comment]
LGTM

**Pull request merged**
