### PR TITLE
Fix asset removal

### PR DESCRIPTION
**Pull request by bensymonds**
This fixes a bug we are seeing in a production deployment: https://app.raygun.io/dashboard/4ce5ze/errors/878707352.

There is already a [spec](https://github.com/withassociates/slices/blob/i18n-fix-asset-removal/spec/regression/asset_deletion_spec.rb), and it passes. The problem is to do with the way the data was previously stored in the db. I haven't got it quite figured out, but it's related to whether there is already a `nil` in the database, and what Mongoid does with `attributes` in that case. Because it's a data problem, I don't think it's worth adding a spec to cover this - it's not an "expected" situation. We should just fix up the data in the db and that's it. Do you see what I mean?

### CODE REVIEW

**Comment by bensymonds** [comment]
This is an actual bug in the i18n stuff, so please take a look.

**Comment by jgwhite** [comment]
Do you have a reference for the bug? Would be good to see how this misbehaved before the patch. Or possibly a regression test if there’s time.

**Comment by bensymonds** [comment]
@jgwhite yeah my apologies, I was far too lazy with this. I've updated the description with more info.

**Comment by erino** [comment]
:+1:

**Pull request merged**
