### PR TITLE
Correct sitemaps helper

### PR DESCRIPTION
**Pull request by calumgunn**

### CODE REVIEW

**Comment by bensymonds** [comment]
I reckon add this PR to the changelog entry (i.e. have the changelog entry list both PRs).

**Comment by calumgunn** [comment]
@bensymonds Do we need to go to 2.0.2 or can we update 2.0.1?

**Comment by bensymonds** [comment]
Ok yeah, good point. It has to be 2.0.2 so that means a new changelog entry then.

**Comment by jgwhite** [comment]
LGTM

**Pull request merged**
