### PR TITLE
Ensure that net-ssh 3 is not used with ruby19

### PR DESCRIPTION
**Pull request by erino**

### CODE REVIEW

**Comment by bensymonds** [comment]
What's the problem with it? Also it's a bit minging to have to add it to the Gemfile. I wish there was another way...

**Comment by erino** [comment]
Net-ssh 3 is only compatible with ruby 2 and above, and that's breaking the build: https://travis-ci.org/withassociates/slices/jobs/88124657

**Comment by calumgunn** [comment]
:+1:

**Comment by erino** [comment]
As ruby 1.9.3 is no longer supported we're going to drop support for that instead https://github.com/withassociates/slices/pull/133

**Pull request closed without merging**
