### PR TITLE
Add class for localising existing pages

### PR DESCRIPTION
**Pull request by erino**
This is the same as #114 but with `master` as the base branch.

### CODE REVIEW

**Comment by calumgunn** [comment]
:+1:

**Comment by bensymonds** [comment]
What about my comments in https://github.com/withassociates/slices/pull/114 description? I think there is still a case to be made _not_ to keep it - is the maintenance and upkeep of it worth it? If we _do_ decide to keep it around I think we have to decide on a few things:

* location in the project (`lib/slices` is a bit generic)
* whether to add specs (answer: yes)

**Comment by erino** [comment]
I wonder if this is more of a Mongoid concern rather then Slices? This is a data migration because adding `localize: true` to a field isn't backwards compatiable in Mongoid 3

Maybe we could link to a gist containing this code as an example of how to migrate data.

**Comment by calumgunn** [comment]
I'm fine with leaving this out.

**Comment by bensymonds** [comment]
I just noticed there are specs already, so ignore that point in my previous comment :dizzy_face:

**Comment by jgwhite** [comment]
@bensymonds on Jan 14 2016:

> i’m wondering whether we just have i18n turned on the whole time in slices
>
> so then mongoid is localising all fields from the start
>
> so you don’t need something like [this PR] if you decide to add a language half-way through a project

Given the above, what it be more appropriate to package this as a separate gem?

**Comment by jgwhite** [comment]
I’m picturing a one-off process of:

**Comment by jgwhite** [comment]
Sorry, pressed the wrong button for the hundredth time.

**Comment by bensymonds** [comment]
Haha yeah I do that. I think it's because the "Comment" button looks so much like the "Merge" button, so you automatically go to the other one.

Well if we do just localise from the start, then this migration becomes part of upgrading Slices. So maybe then we can just put it in some upgrade notes somewhere?

**Comment by jgwhite** [comment]
@bensymonds that sounds reasonable to me.

**Comment by jgwhite** [comment]
What do y’all think of:

- Adding a rake task to this PR
- Adding a note about said task to [internationalization.md](https://github.com/withassociates/slices/blob/master/guides/internationalization.md) in this PR
- Merging and shipping v2

**Comment by jgwhite** [comment]
LGTM

**Pull request merged**
