### PR TITLE
Rewrite README

### PR DESCRIPTION
**Pull request by jgwhite**

### CODE REVIEW

**Comment by erino** [comment]
:+1:

**Comment by calumgunn** [comment]
Yes!

**Comment by jgwhite** [comment]
The README as it stands doubles up on the getting started guide. We should have one or the other. @withassociates/with-core which is most useful?

**Comment by bensymonds** [comment]
I think I vote readme. People will come to the repo and want to see something representative (of using slices) quickly (that's what I look for when looking at a library, anyway). I would bet that a lot of people would drop off before that extra click through to the guide. On the same basis I would put some basic slice creation examples in the readme too. Then maybe the guides can go into more detail, but the first thing each one does is link back to the relevant section of the readme.

**Comment by jgwhite** [comment]
@bensymonds agreed

**Comment by jgwhite** [comment]
Ready for another review.

**Comment by calumgunn** [comment]
:+1: Wicked.

**Comment by erino** [comment]
@jgwhite can you update the year to 2016

**Comment by jgwhite** [comment]
@erino good spot

**Comment by calumgunn** [comment]
do it

**Pull request merged**
