### PR TITLE
Add class for localising existing pages

### PR DESCRIPTION
**Pull request by bensymonds**
Lifted from a project using the i18n stuff and modified slightly.

This is a helper class, used in a migration probably. Is `lib/slices` the best place for it? Do we want to provide/support something like this at all? In theory we could just put a note in the readme/changelog saying "you need to migrate your data if you enable i18n stuff"...

### CODE REVIEW

**Comment by jgwhite** [comment]
Could we add documentation in with this PR? A couple of sentences and code samples in the README would be awesome.

**Comment by calumgunn** [comment]
:+1:

**Comment by bensymonds** [comment]
I know this is merged, but only into `i18n-ui-v2` so still worth having this conversation (because we still have the opportunity to mess with it or remove it completely): what about my comments in the PR description? I think there is still a case to be made _not_ to keep it - is the maintenance and upkeep of it worth it? If we _do_ decide to keep it around I think we have to decide on a few things:

* location in the project (`lib/slices` is a bit generic)
* whether to add specs (answer: yes)

**Comment by bensymonds** [comment]
Actually I'm confused - it says this is merged into `i18n-ui-v2`. And https://github.com/withassociates/slices/pull/107 says `i18n-ui-v2` is merged into `master`. But these commits are not in `master`. If you look at when github says the merges happened, the former happened _after_ the latter. So it makes sense that they're not in `master`. But also they're not in `i18n-ui-v2`. So has something been force-pushed at some point and the commits lost (from those branches - obviously they are still around in git somewhere and so can be got back)?

**Comment by bensymonds** [comment]
Argh ok I should really read all my emails before commenting. https://github.com/withassociates/slices/pull/144.

**Pull request merged**
