### PR TITLE
Switch to CircleCI

### PR DESCRIPTION
**Pull request by calumgunn**

### CODE REVIEW

**Comment by erino** [comment]
@calumgunn can you see if it's possible to test with multiple versions of ruby? as per https://github.com/withassociates/slices/blob/master/.travis.yml#L2

**Comment by calumgunn** [comment]
@erino Got it testing multiple rubies -- but parallelism seems like a difficult one!

**Comment by bensymonds** [comment]
We should bring across the "delete gemfile.lock etc." functionality over to circleci too.

**Comment by bensymonds** [comment]
If it's hard to get the same behaviour (including parallelism) on circleci then I think it's fine to stay on travis. It wasn't really a problem (in my opinion).

**Comment by calumgunn** [comment]
@bensymonds Feast yer eyes, now running with parallelism!

**Comment by bensymonds** [comment]
@calumgunn well ok, seems a bit hacky though. So circleci doesn't have any first class support for building multiple ruby versions in parallel? It just makes me wonder whether Travis is the better choice because it has more features for projects like Slices (or libraries in general). Ok so we got parallel ruby builds working, but are there going to be more problems in future?

If we do go with circleci, there are some other things we should check - see the [recent history](https://github.com/withassociates/slices/commits/39a9c37edd05bae80b987fe772a02c404f1a2943/.travis.yml) of `.travis.yml`. Things like:

* it looks like circleci caches the bundled gems, which is good. But in later builds will the gems get updated to the latest versions? We want this, to make sure we're always testing Slices against them. In travis we had to add a `bundle update` in there, which seemed to do the job.
* do we always get the latest bundler version? In travis there was an issue where the container just came with some old version which wasn't compatible.
* in circle ci there is a step which does this:

```
rvm gemset use global && gem uninstall bundler -ax && gem install bundler && gem list --local
```

In all three parallel builds, the output from this command includes:

```
Using ruby-2.1.6 with gemset global
```

That seems a little sketchy given we're meant to be using different ruby versions in each one. We need to make sure it's all working as expected.

**Comment by erino** [comment]
I'd be inclined to wait until Circle has support for matrix builds. Hacking support for something that isn't supported natively is likely to cause problems in the future.

**Comment by calumgunn** [comment]
I'm inclined to agree. Just perused a few "solutions" that are also really hacky...

**Comment by bensymonds** [comment]
Cool. Close this and disable the project in circleci then! Then I can get a nice green button in #152.

**Comment by calumgunn** [comment]
BURN IT DOWN

**Pull request closed without merging**
