### PR TITLE
Remove rack utf8 fix

### PR DESCRIPTION
**Pull request by bensymonds**
It's in quotes because we're not really sure what it was for now. But we probably don't need it (we'll find out if we do... hopefully).

### CODE REVIEW

**Comment by jgwhite** [comment]
I am 100% certain we don’t need this any more.

**Comment by bensymonds** [comment]
Haha ok sorry, do you want me to rewrite the commit message to reflect that certainty?

**Comment by jgwhite** [comment]
Looks like it was this: https://experiments.openhood.com/ruby/rack/2010/07/15/rack-test-warning/

Not even a bug… just a noisy warning!

**Comment by bensymonds** [comment]
@jgwhite good sleuthing. I don't see any warning now when running the specs with ruby 1.9.3. I guess something (everything) has moved on so it's not generated any more. We could figure out what changed to be 100% sure... or we could just merge and see what happens. I think the latter. You?

**Comment by jgwhite** [comment]
The latter.

**Comment by bensymonds** [comment]
:+1: thanks.

**Pull request merged**
