### PR TITLE
Run travis build against latest ruby 2.1 and 2.2

### PR DESCRIPTION
**Pull request by bensymonds**
Depends on https://github.com/withassociates/slices/pull/120.

Copied from https://github.com/rails/rails/blob/4-2-stable/.travis.yml#L22 (except I don't think we care about `ruby-head`).

### CODE REVIEW

**Comment by bensymonds** [comment]
Oh yeah, need to get latest rails 3.2 for ruby 2.2 support!

**Comment by erino** [comment]
Add that [here](https://github.com/withassociates/slices/blob/master/slices.gemspec#L25) and in the [Readme](https://github.com/withassociates/slices/blob/master/README.md#L25)

**Comment by bensymonds** [comment]
Is it definitely ok to _require_ rails 3.2.22? I mean, Slices itself doesn't require it. You only need it if you want to run ruby 2.2. So maybe we can leave the gemspec alone and only update the `Gemfile.lock`..?

**Comment by bensymonds** [comment]
To clarify what's going on here: to get ruby 2.2 building we need to add `test-unit` gem because it was removed. To add `test-unit` gem we need to upgrade to newer version of rspec, because we need [this](https://github.com/rspec/rspec-rails/blob/fc33b5073d13e2eca31c83d20e0f215134d4540a/lib/rspec/rails/adapters.rb#L9) (otherwise it runs after specs and causes an error). Rspec upgrade is in [separate PR](https://github.com/withassociates/slices/pull/120) (because it's really a distinct change).

**Comment by bensymonds** [comment]
This is good to go now I think. I agree we should update the readme, but it's no longer related to ruby 2.2 so going to do it later.

**Comment by bensymonds** [comment]
@erino waiting for you on this one.

**Comment by erino** [comment]
LGTM

**Pull request merged**
