### PR TITLE
Add in-repo guides

### LINKED ISSUE #141: [RFC] Replace wiki with in-repo guides
## Summary

Move the documentation from the wiki to a new directory in the project called `doc` or `guides`. Do some spring cleaning in the process.

## Motivation

Documentation generated from inline comments is great but there is still value in a set of “guides” organised in a cookbook style. This is the purpose the wiki currently serves. Unfortunately, the wiki has gone untended and has fallen out of sync. In part, this is because the wiki is independent of the codebase and easily ignored. Moving the documentation from the wiki into the repo will help us version the two in lockstep.

## Detailed Design

We create a new directory in the project called `doc` or `guides` and add in all guides from the wiki that are still relevant/accurate.

With this in place, any PRs that introduce significant new APIs should include relevant patches to the guides.

## Drawbacks

This does not change the fact that the guides need attention and maintenance. It does not magically fix the problem of keeping the two in sync, but it will allow people to view the guides as they stood at a particular tag or version.

## Alternatives

Leave the wiki in place but pay it more attention.

## Unresolved questions

None at this time.

### PR DESCRIPTION
**Pull request by jgwhite**
For a preview, check out: https://github.com/withassociates/slices/tree/in-repo-guides/guides

Closes #141

### CODE REVIEW

**Comment by jgwhite** [comment]
@withassociates/with-core what do you reckon?

**Comment by calumgunn** [comment]
I'm into it. Is it worth punching up or bringing up to date before merging?

**Comment by jgwhite** [comment]
@calumgunn I made a bunch of quick updates and dropped some stuff that was really old. If we aim for perfection I fear it’ll remain as an open pull request for ages. I propose incremental improvements once merged.

**Comment by calumgunn** [comment]
:+1: Fine with that!

**Comment by bensymonds** [comment]
Me too :+1:

**Pull request merged**
